runtime: custom
env: flex
service: voice-agent

instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65

entrypoint: python main.py start